### ISSUE TITLE
.log() to return an array of files

### ISSUE THREAD

**Issue by antonioaguilar** [stefanpenner/broccoli-stew#102]
I'm trying to use Broccoli to automatically populate source scripts in an index.html file. I'm new to Broccoli and noticed that it is quite tricky to get the list of files contained in a tree. I haven't been able to find a plugin that could do this in Broccoli. Then I found your plugin and I think it could help. 

I noticed that .log() outputs the matched files in the tree/node directly to stdout. Is it possible to include an option in .log() to return the output as an array of strings containing the matched files, for example:

``` javascript
var Funnel = require('broccoli-funnel');
var Log = require('broccoli-stew').log;

var appFiles = new Funnel('src/app', { include: ['**/*.js'] });
var fileArray = Log(appFiles, { output: 'array' });

console.log(fileArray);
// fileArray = ['src/app/file1.js', 'src/app/file2.js', ... ]

```

There are situations where we only want to work with the list of files that matched a tree instead of the full tree object.

**Comment by zackthehuman** [comment]
I like the idea, but I don't think it would be possible to implement it the way you've proposed. `log` takes in a `node` and _is itself_ a `node`. I needs to be part of a broccoli pipeline to effectively process its input `node`, and the broccoli build itself _may_ be asynchronous, and you see where this is going...

If you wanted to populate a list of source scripts into an `index.html` file you would be better off just writing a simple broccoli plugin that takes two input `nodes`, one for the `index.html` and another for the list of source files, and then just reading all of the paths from the input node and writing out to the file coming from the `index.html` node.

**Comment by stefanpenner** [comment]
In theory one could create a log helper that also forced a build right there and then.

something like:

```
buildAndLog(tree).then(files => console.log(files));
```
