### ISSUE TITLE
`stew.map` doesn't gracefully handle binary files.

### ISSUE THREAD

**Issue by nathanhammond** [stefanpenner/broccoli-stew#134]
This doesn't play nicely with binary files:

```javascript
stew.map(tree, function replacer(content) {
  return content;
});
```

**Comment by rwjblue** [comment]
FWIW, this was an issue in broccoli-filter as well, I'll dig up how we fixed it / worked around it and report back.

**Comment by nathanhammond** [comment]
I _think_ if we blindly turn it back into a buffer it may work? Something like `Buffer.from(content, inputEncoding);` (`inputEncoding` is set by default)? Note, this looks like it would be addressed in `broccoli-filter` after actually looking into it.

The `processString` method (before even showing up in `broccoli-stew`) already has the binary converted to a string, so this would possibly "undo" that.

(All of this is thinking out load since I didn't actually read the docs on `Buffer`s.)

**Comment by stefanpenner** [comment]
i suspect us dealing with strings directly here was a mistake (my bad). Using buffers by default may have been slightly less ergonomic, but likely better. Likely needs some design.

**Comment by stefanpenner** [comment]
I think this is just how `map` works. In theory we could add `stew.mapBuffer` or something, that exposes the raw buffer and lets the user decide...
