### ISSUE TITLE
add `rm`

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-stew#23]
```
rm(tree, glob...);
rm(tree, 'file.txt');
rm(tree, 'file.txt'. 'file2.txt');
rm(tree, '*.txt'. 'file.js');
rm(tree, '*.txt'. '!file.txt'); // should remove all txt files except for file.txt
```

**Comment by rwjblue** [comment]
Implementation notes: this should be implemented as a `Funnel` with an exclude list of the patterns passed in.  Specifically: do **not** actually delete files on disk.

**Comment by stefanpenner** [comment]
@rwjblue correct, these helpers all describe the transform from the current tree to the next.
