### ISSUE TITLE
find should likely also merge if given an array as the first arg.

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-stew#31]
gobble does this, and i think it would be great.

```js
find([
  'lib',
  'apple'
], filter);
```

cc @rich-harris

**Comment by rwjblue** [comment]
@stefanpenner - Link to "gobble"?  I'm not familiar with that project...

**Comment by stefanpenner** [comment]
@rich-harris made gobble in frustration with broccoli API.

**Comment by Rich-Harris** [comment]
@rwjblue some context - Gobble is a personal project heavily inspired by Broccoli, I haven't really marketed it/talked about it as I'd like it to become slightly more stable first. I wrote up some of the frustrations @stefanpenner mentioned - https://gist.github.com/Rich-Harris/affa4f9768fd6332d646 - we were talking just now about how we might work together, e.g. as a starting point reimplementing the Gobble API using Broccoli primitives under the hood

**Comment by stefanpenner** [comment]
@Rich-Harris has some great debugging and API niceties in gobble. Also improvements around how various things cache and stuff.

I've tried to convince him to jump to the dark side ;)
