### ISSUE TITLE
idea: log

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-stew#48]
Log is useful for debugging, but it may also be used to leave in for future debugging sessions.

If we look to [debug](https://github.com/visionmedia/debug), we can see the value.

usage:

```js
...
log(lint(tree), { 
  label: 'ember-cli:tree', // label to match on, and print
  debug: true // when true, only log if the label matches process.env.DEBUG (otherwise be a passthrough step
});
...
```

enabling:

```
DEBUG=ember-cli:trees* ember build
```

@chadhietala / @rwjblue  thoughts?

**Comment by chadhietala** [comment]
:+1: PR on it's way.

**Comment by chadhietala** [comment]
#49
