### ISSUE TITLE
add `cat`

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-stew#5]
this would allow someone to quickly `cat` changed files contents into a function for simple transforms

``` js
var tree = cat(tree, function(inputString) { return outputString; })

var dist = cat(tree, function prepend(file) {
  return license + "\n" + file;
});
```

**Comment by stefanpenner** [comment]
the following might be a good starting point:

cat is M:1 transform with the following signature `cat(tree, inputGlobs..., outputFile);`

```
cat(tree, '**/*.js', 'out.js');
cat(tree, '**/*.js', '**/*.es6', 'out.js');
cat(tree, glob1, glob2, globn..., 'out.js');
```

source maps by default would be idea.

questions:

* should we allow a simple callback transform like map?
* what other features might be needed?
* should we support multiple globs like cat(tree, '**/*.js', , ''out.js');

**Comment by stefanpenner** [comment]
I wonder if cat can be even more general purpose.

```js
cat(tree, '**/*.js', transform);
```

where `transform` gets all the needed details passed as args, so any filter can be implemented via it.

@rwjblue / @chadhietala thoughts?

**Comment by Rich-Harris** [comment]
Not sure I understand what the `transform` argument is for - wouldn't it be better to keep cat and map functionality separate? That way at least it's fairly straightforward for cat to generate sourcemaps. Or are you thinking that the transform function would determine the concatenation order, so it could do browserify-esque things?

**Comment by stefanpenner** [comment]
map is 1:1, cat is M:N (primarily M:1) but both likely want to optionally delegate functionality to arbitrary transforms.

```sh
cat **/*.js | es6ModuleBundler > out.js
```
```js
cat(tree, '**/*.js',  es6ModuleBundler(options), 'out.js'); // M:1
```

```js
map(tree, '**/*.js',  6to5(options)); // 1:1
```

**Comment by chadhietala** [comment]
In the examples above aren't we forcing transforms to be closures? What might be better is to just do.

```js
function pipeline(tree) {
  var es6 = 6to5(tree, {...});
  es6 = es3SafeRecast(es6);
  return write('out.js');
}

var dist = cat(tree, '**/*.js', ...moreGlobs, pipeline);
```
This approach is leaky though because the developer needs to know that they need to return a `write` call from the pipeline.

The approach below forces developers into defining a resulting file like in the stdout example above. 

```js
function pipeline(tree) {
  var es6 = 6to5(tree, {...});
  return es3SafeRecast(es6)
}

var dist = cat(tree, '**/*.js', ...moreGlobs, pipeline, 'out.js');
// or
var dist = cat(tree, '**/*.js', ...moreGlobs, 'out.js');
```

**Comment by chadhietala** [comment]
I suppose we could create `write` method that allowed to do M:N through the pipeline?

**Comment by stefanpenner** [comment]
hmm nice, i like the, `string` as nth arg, being M:1, function/closure return arbitrary tree that can be M:1 or M:N.

**Comment by stefanpenner** [comment]
https://www.npmjs.com/package/magic-string might be interesting re: source maps cc @chadhietala

**Comment by chadhietala** [comment]
Comparing the source of fast-source-map-concat and magic string, it seems magic string sourcemap concating would be faster.
