### ISSUE TITLE
option to set root path for output

### ISSUE THREAD

**Issue by aceofspades** [stefanpenner/broccoli-stew#50]
I'd like to place l DEBUG- files to be in a single ignorable subdirectory.

BTW thanks a lot for this, extremely useful

**Comment by rwjblue** [comment]
Add the following to your `.gitignore`:

```
DEBUG-*
```

**Comment by aceofspades** [comment]
The impetus here was for controlling structural/semantic scans and search results within source trees. (I should have said full path not subdirectory). I'm finding it might be beneficial and performant enough to leave debug output around in dev (#48)

**Comment by aceofspades** [comment]
In case anyone else is interested https://github.com/aceofspades/broccoli-stew/commit/a405faeb0f6e3052e41bb72a4511adb6f5cd19da
