### ISSUE TITLE
Debug does nothing unless "triggered" - ember-cli 0.1.15

### ISSUE THREAD

**Issue by gonvaled** [stefanpenner/broccoli-stew#56]
```
/* global require, module */

var find  = require('broccoli-stew').find;
var debug = require('broccoli-stew').debug;

var tree = find('app/**/*.js');
var debugTree = debug(tree, {name: 'tree'});

module.exports = tree;
```

This produces nothing. To get debug to output anything, I need to completely change my Brocfile, and do, for example:

```
module.exports = debugTree;
```

Which I assume triggers the tree. This is counterintuitive (I expected that just by declaring debugTree it would trigger), and inconvenient: a single debug line is not enough; instead, I need to change several places of the Brocfile. For a complex Brocfile, where the problem is not obvious, it means lots of tampering, putting debug trees, and placing them in the export chain correctly, which is in itself error-prone, and means we need to debug the debugging.

What I would expect is that just by declaring the debug it would produce a debug output. If that is not possible for any technical reason, at least something like:

```
var debugTree = debug(tree, {name: 'tree'}).trigger();
```

Would be a good compromise. Maybe this already exists, but I can not find it documented.

The same applies to log by the way (which, as filed in a previous issue, is not even triggered when put in the export chain)

**Comment by jmera** [comment]
:+1: also expected this behavior

**Comment by stefanpenner** [comment]
this is expected behavior, and documented as such.

**Comment by alanhogan** [comment]
Could change the function name to `logOnAccess`, `debugOnAccess` or some such
