### ISSUE TITLE
Log doesn't appear to do anything

### ISSUE THREAD

**Issue by blesh** [stefanpenner/broccoli-stew#59]
I'm sure it's some sort of incompatibility, but I'm not getting an error or any output:

```js
var stew = require('broccoli-stew');

var log = stew.log;
var find = stew.find;

log(find('/src/**/*.js'), { output: 'tree' });
```

- broccoli-stew 0.2.1
- broccoli 0.15.0

Node `v0.10.35`

**Comment by stefanpenner** [comment]
Cc @chadhietala

**Comment by chadhietala** [comment]
log returns the tree you pass into it. Something like the following should work.

```
var stew = require('broccoli-stew');

var log = stew.log;
var find = stew.find;

var src = log(find('/src/**/*.js'), { output: 'tree' });

module.exports = src;
```

**Comment by stefanpenner** [comment]
seems like we need a doc addition here.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/broccoli-stew/commit/f59d97cdfa39c211f555968d1486d1d9a399859d may help?  @blesh would love your input.

**Comment by blesh** [comment]
Ah ha!  That was it.

I was thinking "log" was more like every other logging function (ala console.log). I wasn't aware I had to export the tree to get it to log. It makes sense now that I think about it. I was busy thinking about the problem I was solving when I wanted to log out the tree at the time.

**Comment by stefanpenner** [comment]
@blesh my bad, would the updated docs help others?

**Comment by blesh** [comment]
Perhaps. I think that's the only one that I was just like "Ah, I'm solving some other problem, I need to log something out!" and just *assumed* console.log behavior.

**Comment by timmfin** [comment]
I agree that mentioning it the docs would help. Even better would be a couple quick examples. The main two approaches that I can think of...

```javascript
// Option 1, wrap your existing trees
var otherTree = stew.log(SomeFilter(inputTree), { /* log options */});
var finalTree =  stew.log(AnotherFilter(otherTree), { /* log options */});

// Option 2 keep track of all of your log trees and merge them later
var logTrees = [];

var otherTree = SomeFilter(inputTree);
logTrees.push(stew.log(otherTree, { /* ... */ });

var yetAnotherTree = AnotherFilter(otherTree);
logTrees.push(stew.log(yetAnotherTree, { /* ... */ });

var finalTree = mergeTrees([yetAnotherTree].concat(logTrees))
```

I've been using option 2 more lately, I like how it puts all of the log output at the end of the build (also I was running into an issue with option 1 when nested many layers deep, but I suspect that was related to this problem [I ran into with broccoli-caching-writer](https://github.com/ember-cli/broccoli-caching-writer/pull/31#issuecomment-78569901)).

**Comment by stefanpenner** [comment]
i did add a small doc improvement: https://github.com/stefanpenner/broccoli-stew/blob/master/lib/log.js#L13-L17

but I admit not being a fantastic doc writer, and would love some further suggestions/contributions.

**Comment by blesh** [comment]
Or even:

```js
// NOTE: If you don't export the logged tree, it won't log the tree.
```

**Comment by stefanpenner** [comment]
@blesh i'll buy you a beer the next time i see you if you submit a pr

**Comment by blesh** [comment]
LOL 🍻 you caught me in the middle of RxJS work, I'll submit something tomorrow. If not, you can hassle me on the Tweeterz
