### ISSUE TITLE
More thorough readme/intro

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-stew#66]
Stuff to cover
- how to think about broccoli and broccoli-stew
  - figure out a good way to describe the virtual layered FS via symlinks concept, and how stew tries to give us unix inspired helpers to mutate this file system
- some examples, and common patterns
- some real-world example
  - https://github.com/tildeio/rsvp.js/blob/master/Brocfile.js
  - https://github.com/krisselden/dag-map/pull/4 
  - https://github.com/ebryn/backburner.js/pull/129

cc @igorminar

**Comment by IgorMinar** [comment]
I would reprioritize the intro. Show me what this is and how to use it and then tell me how to think about it.

Most developers when they are doing just one off task, don't care about why, they only care about how. However when they return back todo more, they want to understand why.

**Comment by stefanpenner** [comment]
i think the why / how are entangled, but I suspect a brief Why followed by more case/case hows will satisfy your concerns?
