### ISSUE TITLE
[Idea] Introduce zip()

### ISSUE THREAD

**Issue by chadhietala** [stefanpenner/broccoli-stew#77]
Given 2 arrays of trees with the same inputPaths, zip them together using `mergeTrees` from right to left leaving one array of N merged trees.

```
var zippedTrees = stew.zip(['tree1', 'tree2'], ['tree1', 'tree2']);
// merged ['tree1', 'tree2']
```

**Comment by stefanpenner** [comment]
@chadhietala so basically flatMap ?

**Comment by chadhietala** [comment]
@stefanpenner It's more like `zip` then `flatMap`. FlatMap works on list of lists to create a single list. Zip takes two lists or sequences and merges them into a List of pairs.

```
flatMap([[1,2,3], [4,5,6]], (x) => x * x) // [1, 4, 9, 16, 25, 36]
```

```
zip([1,2,3], [4,5,6]) // [[1,4], [2,5], [3,6]]
```

It's the same type of operation except our merge creates a merged tree which is a pair of trees.

**Comment by stefanpenner** [comment]
:+1:

**Comment by stefanpenner** [comment]
@chadhietala is this still important? I have not run into this use-case myself, have you wanted it again recently?
