### ISSUE TITLE
Exclude pods from builds in Brocfile

### ISSUE THREAD

**Issue by WooDzu** [stefanpenner/broccoli-stew#78]
As advised by @stefanpenner in [this stackoverflow question](http://stackoverflow.com/questions/30686368/exclude-folders-from-builds-in-brocfile) I'd like to report that excluding ember pods from Broccoli trees doesn't appear to be working.

Let say we have the following structure:
 - /app/modules/components
 - /app/modules/pod1
 - /app/modules/pod2
 - /app/modules/pod3

And this brocfile:
```js
var EmberApp = require('ember-cli/lib/broccoli/ember-app');
var app = new EmberApp();

var Stew = require('broccoli-stew');
module.exports = Stew.rm(app.toTree(), 'app/modules/pod1', 'app/modules/pod2');
```
I'd expected the above should exclude `app/modules/pod1` and `app/modules/pod2` from ember app tree, leaving `app/modules/pod3` only but it does not.

Made a repository to repro the issue:
https://github.com/WooDzu/ember-exclude-pod/tree/broccoli-stew

**Comment by stefanpenner** [comment]
> module.exports = Stew.rm(app.toTree(), 'app/modules/pod1', 'app/modules/pod2');

looks like you are missing the globs

**Comment by WooDzu** [comment]
Here's what I've tried so far:
```js
Stew.rm(app.toTree(), 'app/modules/pod1', 'app/modules/pod2');
Stew.rm(app.toTree(), 'app/modules/pod1/*', 'app/modules/pod2/*');
Stew.rm(app.toTree(), 'app/modules/pod1/**', 'app/modules/pod2/**');
Stew.rm(app.toTree(), 'app/modules/{pod1,pod2}');
Stew.rm(app.toTree(), 'app/modules/{pod1,pod2}/*');
Stew.rm(app.toTree(), 'app/modules/{pod1,pod2}/**');
```
Just double checked all of the above to make sure I didn't miss any.

**Comment by stefanpenner** [comment]
you are correct, this does not appear to be an broccoli-stew issue, rather toTree() has already merged all the files so its to late to remove files.

**Comment by stefanpenner** [comment]
its the `addon.addonPostprocessTree`
