### ISSUE TITLE
I could swear .log has unwanted side effects.

### ISSUE THREAD

**Issue by alanhogan** [stefanpenner/broccoli-stew#85]
Hey, 

hate to file a crazy issue like this, but in theory, shouldn’t these two Brocfile.js excerpts work _exactly the same_ except for the console outputting a tree?

``` js
// No log

function processEyeglass(tree, options) {
  return new BroccoliEyeglass(tree, { /* opts */ });
}
```

``` js
// with log

function processEyeglass(tree, options) {
  var loggedTree = stew.log(tree, { output: 'tree', label: 'brocEyeglassLogTree' });

  return new BroccoliEyeglass(loggedTree, { /* opts */ });
}
```

But for some reason I don’t understand, the tree itself seems to change significantly.  Instead of attempting to compile my Sass, now BroccoliEyeglass seems to return the input tree. Exactly.

any idea what’s going on?

**Comment by stefanpenner** [comment]
I believe @chadhietala and myself have also observed this.

**Comment by timmfin** [comment]
I've also seen this, pretty sure with another broccoli-caching-writer based plugin, and IIRC I strongly suspected [CoreObject shenanigans](https://github.com/ember-cli/broccoli-caching-writer/pull/31#issuecomment-78569901).

**Comment by alanhogan** [comment]
You could well be on the right track, @timmfin … I just fixed a weird bug in a module by updating broccoli-caching-writer: sass-eyeglass/broccoli-eyeglass#15

**Comment by stefanpenner** [comment]
#147 makes log just symlink the root directory, not sure we can do anything less... Maybe with some lower level API's from broccoli...

I think the new one should be fine. Closing for now (i expect to release a new version tonight)
